// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAysQ5cNBA3_FaUITPf2e8k28SvBMZmPBQ',
    appId: '1:205449264007:web:997935dd1a2b4c4b74f122',
    messagingSenderId: '205449264007',
    projectId: 'warkop-database',
    authDomain: 'warkop-database.firebaseapp.com',
    storageBucket: 'warkop-database.firebasestorage.app',
    measurementId: 'G-5SC2KXPVJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiTqfRm5KQZZV_rmgjrlrpidAMi5Vrf4',
    appId: '1:205449264007:android:5daf1cd07cba570574f122',
    messagingSenderId: '205449264007',
    projectId: 'warkop-database',
    storageBucket: 'warkop-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1C4MgUVCWcMMKTW2aYhISOVG0kOMJEg',
    appId: '1:205449264007:ios:c888e422b68492cf74f122',
    messagingSenderId: '205449264007',
    projectId: 'warkop-database',
    storageBucket: 'warkop-database.firebasestorage.app',
    iosBundleId: 'com.example.warkopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1C4MgUVCWcMMKTW2aYhISOVG0kOMJEg',
    appId: '1:205449264007:ios:c888e422b68492cf74f122',
    messagingSenderId: '205449264007',
    projectId: 'warkop-database',
    storageBucket: 'warkop-database.firebasestorage.app',
    iosBundleId: 'com.example.warkopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAysQ5cNBA3_FaUITPf2e8k28SvBMZmPBQ',
    appId: '1:205449264007:web:b9cd75806caf3d7074f122',
    messagingSenderId: '205449264007',
    projectId: 'warkop-database',
    authDomain: 'warkop-database.firebaseapp.com',
    storageBucket: 'warkop-database.firebasestorage.app',
    measurementId: 'G-YGTE7PNK80',
  );
}
